version: '3.8'

services:
  oc_blog_php:
    container_name: oc_blog_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/srv:rw

  oc_blog_db:
    container_name: oc_blog_db
    image: mariadb:10.5.9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sulli
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: oc_blog
    ports:
      - 8024:3306

  oc_blog_pma:
    container_name: oc_blog_pma
    image: phpmyadmin
    environment:
      PMA_HOST: oc_blog_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8023:80
    depends_on:
      - oc_blog_db

  oc_blog_nginx:
    container_name: oc_blog_nginx
    image: nginx:1.19.5
    volumes:
      - './public/:/srv/public:ro'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw'
    ports:
      - 8022:80
    depends_on:
      - oc_blog_php
